import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import {buttonVariants} from "@/components/ui/button";
import {SiteHeader} from "@/app/components/site-header";
import {ReactNode} from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
      <ClerkProvider
          appearance={{
            variables: {
              fontSize: "14px",
              colorPrimary: "#000000",
            },
            layout: {},
            elements: {
              input:
                  "flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 shadow-sm transition-colors file:border-0 file:bg-transparent file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50",
              formButtonPrimary: buttonVariants({ variant: "default" }),
              socialButtonsBlockButton: buttonVariants({ variant: "outline" }),
              cardBox: "shadow-sm border border-gray-200 rounded-lg",
            },
          }}
      >
        <html lang="en">
        <body className={inter.className}>
        <SiteHeader />
        {children}
        </body>
        </html>
      </ClerkProvider>
  );
}
